name       : telepathy-idle
version    : 0.2.2
release    : 7
source     :
    - https://github.com/TelepathyIM/telepathy-idle/archive/telepathy-idle-0.2.2.tar.gz : cc42696d03b860f7c40adba9fe3a8689cd33b814df418d72af306871282ba82b
license    : LGPL-2.1-or-later
component  : programming.library
summary    : An IRC connection manager
description: |
    An IRC connection manager
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(python3)
    - pkgconfig(telepathy-glib)
setup      : |
    %meson_configure -Dtwisted_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
