name       : telepathy-idle
version    : 0.2.0
release    : 5
source     :
    - https://telepathy.freedesktop.org/releases/telepathy-idle/telepathy-idle-0.2.0.tar.gz : 3013ad4b38d14ee630b8cc8ada5e95ccaa849b9a6fe15d2eaf6d0717d76f2fab
license    : LGPL-2.1-or-later
component  : programming
summary    : An IRC connection manager
description: |
    An IRC connection manager
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(python-2.7)
    - pkgconfig(telepathy-glib)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
